### ISSUE TITLE
SHA1 LLVM

### ISSUE THREAD

**Issue by wizrides** [benswift/homebrew-extempore#4]
Seems the tar ball has changed again?  Looks like it was rolled back to whatever it was previously - see most recent commit.

Currently getting this on brew install:

==> Downloading http://llvm.org/releases/3.4.1/llvm-3.4.1.src.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 5795bd984399e7368d528166e18f6b71adb12b47
Actual: 3711baa6f5ef9df07418ce76039fc3848a7bde7c
Archive: /Library/Caches/Homebrew/extempore-llvm-3.4.1.tar.gz

**Comment by benswift** [comment]
Ah, thanks for the heads up.  The problem was mine - I had to update all the GH hashes, but llvm isn't downloaded from GH.  But I accidentally changed it as well. Fixed in master.
