### ISSUE TITLE
SHA1 mismatch in extempore.rb

### ISSUE THREAD

**Issue by wizrides** [benswift/homebrew-extempore#5]
Identified another further along in the brew install process:

==> Downloading from https://codeload.github.com/digego/extempore/zip/0.59
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 7f73d99086f91cdee48e75e52d377feb0f3718f6
Actual: 5795bd984399e7368d528166e18f6b71adb12b47

**Comment by benswift** [comment]
Cool, fixed.  Ah, the joys of maintaining one's own homebrew tap.

**Comment by wizrides** [comment]
Thanks man! Very much appreciated.
