### ISSUE TITLE
Formula.sha1 is disabled

### ISSUE THREAD

**Issue by nsfw** [benswift/homebrew-extempore#7]
Howdy Ben! No luck installing the tap, seems sha1 is deprecated. 

```
brew tap benswift/extempore
==> Tapping benswift/extempore
Cloning into '/usr/local/Homebrew/Library/Taps/benswift/homebrew-extempore'...
remote: Counting objects: 11, done.        
remote: Compressing objects: 100% (11/11), done.        
remote: Total 11 (delta 0), reused 4 (delta 0), pack-reused 0        
Unpacking objects: 100% (11/11), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/benswift/homebrew-extempore/extempore-llvm341.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/benswift/homebrew-extempore/extempore-llvm341.rb:6:in `<class:ExtemporeLlvm341>'
Please report this to the benswift/extempore tap!
Error: Cannot tap benswift/extempore: invalid syntax in tap!
bash-3.2$ 
```

**Comment by benswift** [comment]
Hi Scott

Which version of OSX are you on? The homebrew install process is pretty out-of-date (I really should remove it - sorry!). The [build from source](http://digego.github.io/extempore/install.html#build-from-source) should work pretty cleanly on the last couple of versions of OSX, and I highly recommend doing it that way if you can.

**Comment by nsfw** [comment]
10.10.5 Yosemite

And yes, I noticed that the LLVM recipe in the repo is for 3.4.1 but it looks like 3.7 is current for that.

I'll build from source, and maybe I'll see if I can update the homebrew stuff! 

It's been a while, but I've been a Fluxus user, but am looking forward to giving your project a try!

**Comment by benswift** [comment]
Yep, give the build from source stuff a try - let me know how you get on.

If you have any questions, feel free to ping them to the [mailing list](extemporelang@googlegroups.com).
